import json

def mdp_to_json (mdp):

    conditions = mdp.split("\n")
    data = dict()

    for condition in conditions:

        if condition.startswith(";"):
            continue

        condition = condition.split()

        if len(condition) < 3:
            continue

        data[condition[0]] = " ".join(condition[2:])

    return data

def json_to_mdp (data):

    writable = ["; Automatically generated by Chocomacs"]

    for key in data:

        writable.append(key + " = " + str(data[key]))

    return "\n".join(writable)
